// Generated by https://quicktype.io

export interface DashboardSummaryReponse {
    numberOfOrders:       number;
    paidOrders:           number;
    numberOfClients:      number;
    numberOfProducts:     number;
    productsWithNoStock:  number;
    productsWithLowStock: number;
    notPaidOrders:        number;
}
